version: '3.3'
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx/core:/etc/nginx/conf.d
            - /server/yii:/var/www/
            - ./nginx/logs:/var/log/nginx/
            - ./nginx/html:/usr/share/nginx/html/
        links:
            - php
    php:
        build: ./php
        volumes:
        - /server/yii:/var/www/
        container_name: php-fpm

